MobilityDB/MobilityDB

CMakeLists.txt, include/temporal_aggfuncs.h, src/temporal_aggfuncs.c
Using an internal (naïve) implementation of ffsl() for systems without it.
Also, the random()s for aggregation skiplists were too short, so using numbers from GSL instead.
=> Fixed build for systems without ffsl()

.editorconfig
Closes #24 
All settings of `.editorconfig` file need discussion so they can be adjusted to your coding style.
I'll mark it as draft until such a discussion is finished.
=> Adding an editor config file

.github/workflows/check-code.yml, tools/scripts/test_license.sh, tools/scripts/test_shell.sh
This adds action checks on:
* licenses
* shell code
Following the same work done on pgRouting in the last week
As you can see here:
https://github.com/cvvergara/MobilityDB/runs/1370853374?check_suite_focus=true
Many files lack license
and from here:
https://github.com/cvvergara/MobilityDB/runs/1370853365?check_suite_focus=true
There are not so many shell warnings
After merging change `tools/scripts/test_license.sh` needs to be updated to the licenses needs.
For example right now it tests for license in `src, `include and `points` directories
And for the documentation what is there is what I use for pgRouting (I find .rst which you don't use), because `licensecheck` does not find Creative Commons, I just find it, and using `licensecheck` to find the copyright
=> Adding actions to check licenses and shell script

.github/workflows/macos.yml, CMakeLists.txt, cmake/FindPROJ.cmake
Creating a macos action that will be manually triggered
Because currently only postgis 2.5 is required and macos installs postgis 3
The idea of having this action is to have it ready for when postgis 3 is used.
Do not merge, as this PR currently has many commits that will be squashed to only one commit that solves this issue when it is ready to be merged. Which will be announced on a comment and it will be ready for review.
=> Macos action

.github/workflows/clang.yml, CMakeLists.txt, src/point/tpoint_in.c
Adding an action to compile with clang
- warnings are treated as errors `-DWerror` when Clang is used and its compiled with -DCMAKE_BUILD_TYPE=Debug
- when -DCMAKE_BUILD_TYPE is not Debug warnings will be warnings.
=> Action to compile with clang

CMakeLists.txt, meos/CMakeLists.txt, meos/include/general/meos_catalog.h, meos/include/meos.h, meos/include/meos_export.in.h, meos/include/meos_internal.h, meos/include/meos_internal_export.h, meos/include/pg_ext_defs.in.h, meos/include/pg_int_defs.in.h, meos/include/postgis_ext_defs.in.h, meos/src/general/set_ops.c, mobilitydb/CMakeLists.txt
Changes made:
- Add meos.h file for MobilityDB compilation (no need to reconstruct it every time)
- Rename meos.in.h to meos_export.in.h: This file is now only used to construct meos_export.h when building MEOS.
- CMake will now write meos_export.h to the build directory
- Remove the postgres.h import from meos_catalog.h
Installing the library will now write the following files to /usr/local/include/:
1. meos_export.h (renamed to meos.h)
2. meos_internal_export.h (renamed to meos_internal.h)
3. meos_catalog.h
=> Improve compilation and installation of MEOS library

meos/src/point/tpoint_spatialfuncs.c, mobilitydb/test/npoint/expected/087_tnpoint_spatialfuncs_tbl.test.out, mobilitydb/test/point/expected/056_tpoint_spatialfuncs_tbl.test.out
This PR modfies the seg2d_intersection function to avoid the errors caused by floating point precision errors in the old function. The new function is a modified version of the PostGIS function `lw_segment_intersects` and also returns the intersection point in case the two segments intersect at equal endpoints. The intersection point is required in `tpointseq_linear_find_splits` only for this intersection type.
=> Fix seg2d_intersection

.github/workflows/check-code.yml, .github/workflows/clang.yml, .github/workflows/generate_docs.yml, .github/workflows/macos.yml, .github/workflows/pgversion.yml, .github/workflows/windows_msys2.yml
Run workflows in the following conditions:
- Run build and test workflows when source files or build file (CMakeLists.txt) change. Run for all branches on pushes and PR.
- Run licensecheck workflow only when PR to develop or master
- Run doc generation on PR and pushes to master and develop. During PR, generate docs in master-pr or develop-pr folders to avoid overriding the existing documenation.
=> Run workflows only when required

README.md
Using the docker image for [postgis](https://registry.hub.docker.com/r/postgis/postgis/) I wasn't able to compile MobilityDB following the instructions on the README.md file.
By installing two extra packages (namely `libgsl-dev` and `libgeos-dev`) the problems were solved and the instructions work perfectly.
This PR adds those two packages to the README.md instruction.
(Technically speaking, `git` is also required to following the instructions as is. But since it is possible manually download the repository from the web, I think that `git` shouldn't be considered a dependency.)
For the record, these are the errors encountered before installing the two packages:
```
Could NOT find GSL (missing: GSL_INCLUDE_DIR GSL_LIBRARY GSL_CBLAS_LIBRARY)
```
and
```
FindGEOS.cmake: geos-config not …
```
=> Add libgsl and libgeos dependencies to installation instructions

mobilitydb/src/general/span_spgist.c, mobilitydb/src/general/tnumber_spgist.c, mobilitydb/src/point/tpoint_spgist.c, mobilitydb/test/general/expected/011_span_indexes_tbl.test.out, mobilitydb/test/general/expected/044_temporal_indexes_tbl.test.out
Changes:
- Add levels correctly when traversing a kdtree
- Always assume inclusive bounds of the span quadtree nodes. Not as optimal as handling the bounds correctly, but this would sometimes cause empty spans to be created, so this was the simplest fix.
- Use the same code for spam overlaps and contains in both quadtree and kdtree. I believe the code for kdtree was trying to only test one dimension at a time, but it was wrong, so I just used the same code as quadtree. This is similar to what spgist does for tbox and stbox.
=> Fix spgist indices

meos/include/meos.h
Add back setters and getters of intervalstyle and datestyle in meos.h that were lost in #411, the implementations were recovered in #412.
=> Add back intervalstyle and datestyle setters and getters to meos.h

README.md
I only mention the database adapters since MEOS is not mentioned anywhere else in the Readme, so it would be weird to do so here.
The SQLAlchemy extension is no longer supported, and it's addition to PyMEOS will not be soon
=> Update python references in readme to point to PyMEOS

meos/include/postgis_ext_defs.in.h
The previous PR (#441) was not completely ready, as it was missing some pieces to make it usable in PyMEOS.
I've added the definition of `PJ` (copied from the [proj.h header](https://github.com/OSGeo/PROJ/blob/deb1a5720fdfcd50d53c93ffb4011cacb36f2c89/src/proj.h#L221)).
I've checked all versions from 6.1 (the minimum required by MobilityDB) until the last (9.3) and it is defined like this, so I think we're safe.
I've also removed the `#include "proj.h"` since I don't think it's necessary here (although please check :).
=> Add PJ definition in postgis_ext_defs.in.h

meos/include/postgis_ext_defs.in.h, meos/postgres/common/CMakeLists.txt, meos/postgres/port/CMakeLists.txt, meos/postgres/timezone/CMakeLists.txt, meos/postgres/utils/CMakeLists.txt, meos/src/point/pgis_types.c, postgis/liblwgeom/CMakeLists.txt, postgis/libpgcommon/CMakeLists.txt, postgis/ryu/CMakeLists.txt
* This PR adds CMake parameters to hide the Postgis and Postgres functions used by the MEOS library.
* The only exported Postgis function is `geo_get_srid`, which is a MEOS function wrapping the Postgis `gserialized_get_srid` function.
=> Hide Postgis and and Postgres functions in MEOS library

meos/postgres/utils/datetime.c, meos/postgres/utils/formatting.c
Remake of #459
This PR fixes three pointer conversion errors that were reported during compilation of the MEOS library in the macOS env of the conda PR, which uses CLang 16.
They were not being reported because these int-conversion errors were only "upgraded" to default errors in CLang 15 ([see release notes](https://releases.llvm.org/15.0.0/tools/clang/docs/ReleaseNotes.html#improvements-to-clang-s-diagnostics), third to last bullet point)
=> Fix pointer conversion errors reported by CLang 15/16

meos/src/general/error.c
Use `vsnprintf` instead of `vsprintf`, to make sure we don't write more than the size of our buffer.
Currently just truncate the error message in case it overflows, but I left a `TODO` in case we want to change that later.
=> Truncate error message if longer than 1024 characters

meos/src/general/tsequence.c, mobilitydb/src/general/meos_catalog.c
This should fix the issue detected by Bradford Boyle
=> Use self-defined `hash_bytes_uint32` function when using pg12

.github/workflows/macos.yml
Run the MobilityDB tests on both intel- and arm-based macOS.
Explicitely  specify macos versions (`macos-13` and `macos-14`) instead of `macos-latest` (which now, or at least soon, is the same as `macos-14`, see [GitHub docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories))
=> Add arm to macOS workflow

meos/src/point/tpoint_restrict.c, mobilitydb/test/point/expected/056_tpoint_spatialfuncs.test.out, mobilitydb/test/point/expected/076_tpoint_analytics_tbl.test.out, mobilitydb/test/point/queries/056_tpoint_spatialfuncs.test.sql
This PR fixes a bug in atstbox that happened when a tpoint exited and entered the box in two contiguous segments.
For example:
```sql
select astext(atStbox(
tgeompoint '[Point(1 1)@2000-01-01, Point(1 3)@2000-01-02, Point(1 1)@2000-01-03]', 
stbox 'STBOX X((0,0),(2 2))'));
```
Before:
```
astext                                                    
-------------------------------------------------------------------------------------------------------------
{[POINT(1 1)@2000-01-01 00:00:00+01, POINT(1 2)@2000-01-01 12:00:00+01, POINT(1 1)@2000-01-03 00:00:00+01]}
(1 row)
```
After:
```
astext                                                                      
------------------------------------------------------------------------------------------------------------------------------------- …
```
=> Fix bug in atstbox function

meos/src/general/tsequenceset.c
=> Fix tsequenceset_make_gaps for non-exit error handling (Backport of #486)

meos/src/point/tpoint_tile.c
Without the parenthesis, the `+` would be evaluated before the `?` operator.
=> Fix operator precedence bug in spacetime_split

meos/examples/ais_expand.c, meos/examples/ais_generalize.c, meos/examples/ais_transform.c, meos/examples/floatspanset_agg.c, meos/examples/intspan_agg.c, meos/examples/set_agg.c, meos/examples/spanset_conv.c, meos/examples/stbox_tile.c, meos/examples/tbox_tile.c, meos/examples/tfloat_assemble.c, meos/examples/tpoint_assemble.c, meos/examples/ttext_expand.c, meos/src/general/set.c, meos/src/general/temporal_aggfuncs.c, meos/src/general/temporal_analytics.c, meos/src/general/temporal_tile.c, meos/src/general/type_parser.c, meos/src/point/pgis_types.c
While fixing memory leaks in the examples, I realised that the aggregation functions had to be used like this:
```C
SpanSet *ss = state;
state = span_union_transfn(ss, rec.span);
if (ss && state != ss)
free(ss);
```
This does not seem very user-friendly.
Perhaps we should free the input state inside `span_union_transfn` if needed.
This would allow to write simply:
```C
state = span_union_transfn(state, rec.span);
```
Of course we need to explicitly mention it if we free the input state to avoid user errors.
=> Fix memory leaks

meos/include/meos.h
JMEOS and other FFI that use regex pattern matching for extracting functions from the meos header file require an extern keyword in the function signature.  Therefore, adding an extern keyword to all the temporal functions that do not have that results in uniform function extraction across FFIs.
=> Updated meos.h to include extern keyword

meos/include/meos.h, meos/src/point/pgis_types.c
Use directly the bytes (u8) instead of varlena type in geo_as_ewkb.
In the Rust wrapper, I need a fast way to create a `Geos` geometry from a a `GSERIALIZED`, and since getting and parsing the `WKT` is very slow, I want to use `WKB` instead. Unfortunately, currently the function to create a `GSERIALIZED` from a WKB returns a `bytea` (`varlena`), and the function to create the bytes from `bytea` is private. I therefore think that it makes more sense from the user point of view to have the bytes directly returned.
This function is not used in this repository or in any of the wrappers
=> Edit geo_as_ewkb to return standard type instead of bytea

.github/workflows/macos.yml
* Fix macos-13 workflow by reinstalling python 3.12
* Use [tecolicom/actions-use-homebrew-tools](https://github.com/marketplace/actions/install-and-cache-homebrew-tools) to cache homebrew packages and speed up macos workflows
=> Fix macos 13 workflow

mobilitydb/sql/point/058_tpoint_tile.in.sql
Uniformize the name of the arguments for the tiling functions as in 
SELECT spaceTimeTiles(extent(Trip), xsize:=5000, duration:='12 hours') AS rec FROM Trips;
=> Uniformize argument names

meos/src/point/CMakeLists.txt
RTree was previously being compiled when building mobilitydb which is unnecesary. Thus, it was removed and it only compiles the RTree when the `MEOS` flag is on.
=> Removes compilation of RTree in mobilitydb

meos/CMakeLists.txt
Use CMAKE_INSTALL_PREFIX instead of hard-coded paths such as `/usr/lib` or `/opt/homebrew`
=> Use CMAKE_INSTALL_PREFIX in CMakeLists

meos/postgres/port/CMakeLists.txt
=> Do not compile pg_bitutils.c (#610)

mobilitydb/test/scripts/test.cmake
Apply the same change as PostgreSQL in commit [b8ea0f675f35c3f0c2c](https://github.com/postgres/postgres/commit/b8ea0f675f35c3f0c2cf62175517ba0dacad4abd) to fix issue with change in tzdata in release 2024b. This doesn't seem to affect our expected test output, but I couldn't test it on 2024b. Hopefully this is enough.
=> Change timezone from PST8PDT to America/Los_Angeles

.github/workflows/docker-image.yaml
I am still keeping Postgis version at 3.4, because postgis is only building docker images with 3.5 for PG 16 and 17. We can update this later in case they produce images with 3.5 for PG 15 and below.
=> Create docker image for PG 17

meos/postgres/timezone/CMakeLists.txt
Right now `meos_initialize_timezone` does not work in the branch `stable-1.2`. The reason is that the timezone library is not accessible since #447, this make meos throw the following error when trying to use `meos_initialize_timezone`:
```
undefined reference to `meos_initialize_timezone'
```
This is already changed in master since https://github.com/MobilityDB/MobilityDB/pull/634, but it's not fixed. This PR is against stable1.2, so I'm not sure about the consequences of the versioning.
Maybe I should comment line 8?
=> Bring back the timezone pg functions to MEOS to fix meos_initialize_timezone in stable-1.2

meos/CMakeLists.txt
@Davichet-e 
Allow MEOS to be built as a static library by setting `-DBUILD_SHARED_LIBS=off` in cmake
=> Add BUILD_SHARED_LIBS for shared or static library build

.github/workflows/generate_dev_docs.yml, .github/workflows/generate_docs.yml, doxygen/Doxyfile, doxygen/Doxyfile_gha
The github action for the develop documentation wasn't being run, probably due to the syntax used for the paths.
I removed the leading `./` before the path specifications, let's see if this fixed things.
Also, it seems that the version number is hard-coded in the doxygen file instead of being configured from the `mobdb_version.txt` file. I just updated the version to 1.3 for now, but this should be fixed in a future PR.
=> Fix developer documentation generation

.github/workflows/pgversion.yml
- Removes any existing PostgreSQL installations
- Sets a consistent port (PGPORT=5432)
- Installs PostgreSQL from the official repository
- Uses the standard port for all PostgreSQL operations
--------
Problem: 
* the PostgreSQL service was started before configuring its port. Once started, changing the PGPORT environment variable doesn't affect which port the server listens on.
My proposal:
- Removing existing PostgreSQL installations:   So no conflicts between Ubuntu's default PostgreSQL and the version from PostgreSQL's official repository.
- Simplifying port configuration:   Set a fixed port (PGPORT=5432) which is PostgreSQL's default port, eliminating the conditional logic that was causing issues.
Additional Notes:
**This update specifically addresses the port configuration issue and …
=> Fix: correct PG port configuration in pgversion.yml

meos/src/temporal/meos_catalog.c
Fixes #681.
I'm not sure if the NDEBUG guard was there for a particular reason, or if there is another solution, but this fixes the problem.
=> Remove NDEBUG guard for ensure_span_tbox_type and others

meos/examples/read_spatial_ref_sys.c, meos/include/meos.h, meos/src/geo/tspatial_transform_meos.c
Fixes #683.
Convert `SPATIAL_REF_SYS_CSV` from a macro to a global variable, as the ones used for the date order and style, and adds a function to modify it (`meos_set_spatial_ref_sys_csv`).
Also changes the default value of the macros to the proper path in `/usr/local/share` (and not `/usr/local/lib`).
Improves log on load error.
=> Replace macro defining SPATIAL_REF_SYS_CSV with a global variable

meos/include/meos.h
I believe `tfloat_max_value` was missing from meos.h, the function is defined in https://github.com/MobilityDB/MobilityDB/blob/2abab6bd74ab362e3684b480ae7ab2735bd28e81/meos/src/temporal/temporal_meos.c#L615C8-L615C8
=> Add tfloat_max_value

meos/src/temporal/type_in.c, meos/src/temporal/type_out.c, mobilitydb/test/temporal/expected/023_temporal_inout_tbl.test.out, mobilitydb/test/temporal/queries/023_temporal_inout_tbl.test.sql
Each individual commit in this PR contains a specific code change and has a detailed comment. I will try to merge this PR using 'rebase and merge', which avoids an undesirable squash when the commits in a PR have each their own scope and comment.
I'm not sure if this is better than squashing all commits of a PR into a single commit with a single message, but let's try it out and see.
=> Fix big-endian handling for ttext type and refactor code to remove redundancy

mobilitydb/test/scripts/test.cmake
Reverses the order of 'output' and 'expected' files in the diff command to ensure that:
- '+' indicates an unexpected line added to the output.
- '-' indicates a line missing from the output.
=> Swap 'diff' arguments for intuitive test reporting

mobilitydb/src/cbuffer/cbuffer.c, mobilitydb/src/geo/spatialset.c, mobilitydb/src/geo/tgeo_tile.c, mobilitydb/src/geo/tspatial.c, mobilitydb/src/npoint/npoint.c, mobilitydb/src/pose/pose.c, mobilitydb/src/rgeo/trgeo.c, mobilitydb/src/temporal/temporal_tile.c
Change the suffix of shared external SQL functions from '_ext' to '_common' to match PostgreSQL function names having the same behavior
=> Improve external function names to align with PG naming

mobilitydb/sql/general/030_temporal_compops.in.sql
Fixes the issue mentioned by #680.
The commutators of the temporal compops for the `ttext` were wrong. Previously this didn't raise an error, but starting with PG 17, postgres raises an error when two operators have the same commutator. Strangely, this error was only raised when running `pg_upgrade` to go from PG 16 to PG 17, and does not get raised when running `CREATE INSTALL`.
Cherry-pick of c2c5608f4
=> Fix the commutators of the ttext temporal compops (#722)

.github/workflows/pgversion.yml
-  Removes any existing PostgreSQL installations
- Sets a consistent port (PGPORT=5432)
- Installs PostgreSQL from the official repository
- Uses the standard port for all PostgreSQL operations
Cherry-pick of 74a4268471bcad46f9082ba144e48ae68509ca00
=> Fix workflow (#663)

mobilitydb/src/general/span_analyze.c, mobilitydb/src/general/temporal_analyze.c, mobilitydb/src/point/tpoint_analyze.c
Update the calls to `vacuum_delay_point`, which took an additional parameter in PG 18.
Couldn't cherry pick these changes from master as they were part of a larger commit.
=> Update code for PG18
