MobilityDB/MobilityDB

CMakeLists.txt

Not allowing ins-source builds

closes #22 Does not allow in-source builds

---

README.md

Add publication, and preprints.

[closing #32] adding 2020 publications

---

src/temporal.c

Remove merge conflict markers.

---

.github/workflows/pgversion.yml

Proposed changes:
The action will test on:
- postgres: 10,11,12,13
- ubuntu 20 (latest) & 18
- postgis: 2.5
see: https://github.com/cvvergara/MobilityDB/runs/3098174915?check_suite_focus=true

Add action test postgres versions

---

tools/scripts/test_shell.sh

All the files are processed.
There are errors on several files and an issue for each file is going to be opened.

[CI] shell script test process all shell files

---

test/scripts/test.sh
tools/scripts/test_shell.sh

What has been done is described in the commits

Clean up warnings from test.sh

---

include/general/tsequence.h
include/general/tsequenceset.h
include/point/tpoint_spatialfuncs.h
src/general/temporal.c
src/general/temporal_similarity.c
src/general/tsequence.c
src/general/tsequenceset.c
src/npoint/tnpoint_distance.c
src/npoint/tnpoint_spatialfuncs.c
src/npoint/tnpoint_tempspatialrels.c
src/point/projection_gk.c
src/point/stbox.c
src/point/tpoint_aggfuncs.c
src/point/tpoint_analytics.c
src/point/tpoint_boxops.c
src/point/tpoint_distance.c
src/point/tpoint_out.c
src/point/tpoint_spatialfuncs.c
src/point/tpoint_spatialrels.c
src/point/tpoint_tempspatialrels.c
src/point/tpoint_tile.c

This PR also 
* Improves the naming of some functions
* Fix some usage of the PG_FREE_IF_COPY_P macro

Optimize nearestApproachInstant

---

CMakeLists.txt
meos/include/meos_process_ais.c
meos/include/meos_read_ais.c
meos/postgres/common/CMakeLists.txt
meos/postgres/postgres.h
meos/postgres/timezone/CMakeLists.txt
meos/postgres/timezone/pgtz.c

* Add local time zone management

Building MEOS

---

meos/examples/03_meos_assemble_ais.c
meos/examples/04_meos_stream_ais.c
meos/examples/04_meos_stream_file_ais.c

Add MEOS example program.   A simple program that reads AIS data from a CSV file, accumulates the observations in main memory and send the temporal values to a log file when they reach a given number of instants in order to free the memory and ingest the newest observations.

add example streaming in file

---

mobilitydb/src/general/temporal.c

See bug reported in Issue #299

Add SRID to binary representation

---

.github/workflows/windows_msys2.yml
meos/include/general/span.h
meos/include/meos.h
meos/include/meos_internal.h
meos/src/general/span.c
meos/src/general/spanset.c
meos/src/general/tsequence.c
meos/src/general/tsequenceset.c
meos/src/general/type_out.c
meos/src/npoint/tnpoint_static.c
mobilitydb/CMakeLists.txt
mobilitydb/src/general/span.c

Add msys2 build

---

doxygen/Doxyfile
meos/src/general/temporal.c
meos/src/general/tsequence.c
meos/src/general/tsequenceset.c
meos/src/point/tpoint_distance.c
mobilitydb/src/point/geography_functions.c
mobilitydb/test/npoint/expected/082_npointset_tbl.test.out
mobilitydb/test/npoint/queries/082_npointset_tbl.test.sql
mobilitydb/test/point/expected/052_tpoint.test.out
mobilitydb/test/point/expected/056_tpoint_spatialfuncs.test.out
mobilitydb/test/point/queries/056_tpoint_spatialfuncs.test.sql

* Test spatial validity for merge

Support for Proj 9.2

---

meos/include/meos.h
meos/postgres/timezone/pgtz.c
meos/postgres/utils/CMakeLists.txt
meos/postgres/utils/formatting.c
meos/postgres/utils/formatting.h
meos/postgres/utils/timestamp.c
meos/src/general/ttext_textfuncs.c

Code borrowed and adapted from PostgreSQL.
* timestamp(tz) to char
* interval to char
* to timestamp
* to date

Add type formatting to MEOS

---

meos/CMakeLists.txt
meos/src/general/temporal.c

This PR fixes small bugs with MEOS compilationa and running that were added in the last two PR's and are not detected by the MobilityDB tests.

Fix meos compilation

---

meos/CMakeLists.txt
meos/include/meos_internal.h
mobilitydb/CMakeLists.txt

feat: added the MacOS paths in the cmake files of MobilityDB and MEOS
fix: Added const in function spanset_compact in meos_internal.h to match

added the MacOS paths

---

mobilitydb/src/general/meos_catalog.c

- Split oid cache loading between type and operator cache
- Only load type cache on `CREATE EXTENSION` call
- Use `get_extension_schema` and `GetSysCacheOid2` to avoid calls to calls to `PushOverrideSearchPath`

Fix mobilitydb oid cache loading

---

meos/src/point/tpoint_spatialrels.c

Follows PR #463 with similar fixes in `tpoint_spatialrels.c`

Fix variadic function calling for arm64

---

.gitignore
CMakeLists.txt
meos/CMakeLists.txt
meos/postgres/common/CMakeLists.txt
meos/postgres/pg_config.h.in
meos/postgres/port/CMakeLists.txt
meos/postgres/timezone/CMakeLists.txt
meos/postgres/utils/CMakeLists.txt
postgis/libpgcommon/CMakeLists.txt
postgis/postgis_config.h.in
postgis/ryu/CMakeLists.txt

This solves some compilation issues on arm and ios.

Configure pg_config.h using CMake

---

doc/es/temporal_types_spatial.xml
doc/temporal_network_points.xml
doc/temporal_types_spatial.xml
meos/include/meos.h
meos/include/point/tpoint_spatialrels.h
meos/src/point/pgis_types.c
meos/src/point/tpoint_spatialrels.c
mobilitydb/test/npoint/expected/096_tnpoint_spatialrels_tbl.test.out
mobilitydb/test/point/expected/070_tpoint_spatialrels_tbl.test.out
mobilitydb/test/point/queries/070_tpoint_spatialrels_tbl.test.sql

Fix ever/always spatial relationships

---

meos/src/general/type_out.c
mobilitydb/src/general/span_selfuncs.c
mobilitydb/src/general/temporal_selfuncs.c
mobilitydb/src/npoint/tnpoint_gin.c
mobilitydb/src/point/tpoint_selfuncs.c
postgis/liblwgeom/lwhomogenize.c

See discussion at: https://lists.osgeo.org/pipermail/mobilitydb-dev/2024-April/000126.html

Removing develop branch

---

meos/src/point/tpoint_restrict.c
mobilitydb/test/point/expected/056_tpoint_spatialfuncs.test.out
mobilitydb/test/point/expected/076_tpoint_analytics_tbl.test.out
mobilitydb/test/point/queries/056_tpoint_spatialfuncs.test.sql

Fix bug in atstbox function (Backport of #487)

---

mobilitydb/test/scripts/test.cmake

Do not read psql startup file (~/.psqlrc) during tests (Backport of #493)

---

meos/src/point/tpoint_restrict.c
mobilitydb/test/point/expected/056_tpoint_spatialfuncs.test.out
mobilitydb/test/point/queries/056_tpoint_spatialfuncs.test.sql

Solves some edge cases when an instant of a sequence is on the edge of the stbox

Fix edge cases in tpointseq_linear_at_stbox_xyz

---

meos/src/general/type_util.c

Fixes #524
Please see the issue for an explanation of the memory leak.

Fix memory leak in stringarr_to_string

---

meos/src/point/tpoint_spatialfuncs.c
mobilitydb/test/point/expected/056_tpoint_spatialfuncs.test.out
mobilitydb/test/point/queries/056_tpoint_spatialfuncs.test.sql

This fixes the issue raised in #539

Fix edge case bug in trajectory function

---

meos/include/general/temporal_aggfuncs.h
meos/include/general/temporal_tile.h
meos/include/meos.h
meos/include/meos_internal.h
meos/include/npoint/tnpoint_spatialfuncs.h
meos/include/npoint/tnpoint_tempspatialrels.h
meos/src/general/error.c
meos/src/general/skiplist.c
meos/src/general/temporal.c
meos/src/general/temporal_aggfuncs.c
meos/src/general/temporal_modif.c
meos/src/general/temporal_tile.c
meos/src/general/tsequenceset.c
meos/src/general/type_out.c
meos/src/npoint/tnpoint_spatialfuncs.c
meos/src/npoint/tnpoint_tempspatialrels.c
meos/src/point/pgis_types.c
meos/src/point/tpoint_tile.c
meos/src/point/type_srid.c
mobilitydb/src/general/temporal.c

Fixes #545.
I built MEOS and it completed succesfully
- Will this break any wrapper?
- Is there any Regex used in ~PyMEOS~ (confirmed with author) or JMEOS that would make this change a breaking change?

Make some pointers in the parameters constant

---

meos/CMakeLists.txt
tools/meos.pc.in

Add support for pkg-config

---

.github/workflows/macos.yml

Reinstall python after getting the cache otherwise it would not correctly work

GitHub Action - Fix cache usage of macos-13

---

mobilitydb/sql/general/026_tnumber_mathfuncs.in.sql

Fix typo in * operator (#509)

---

.gitignore
meos/CMakeLists.txt
mobilitydb/CMakeLists.txt

Configure files in build dir (#590)

---

.github/workflows/meos.yml

This action compiles and installs MEOS and then also compiles and runs 01_hello_world.c

Add action to check MEOS compilation

---

meos/postgres/timezone/pgtz.c

In `meos_initialize_timezone`, if a timezone is already loaded (`session_timezone` is not `NULL`), it is [freed](https://github.com/MobilityDB/MobilityDB/blob/b71674aafc62620a655b0b08ec7a71041477e773/meos/postgres/timezone/pgtz.c#L457-L458). However, the entry that is freed is also the entry that is stored in the cache, so if the new timezone happens to be the same, the new stored timezone is just freed space, that crashes when calling `meos_finalize` or if changing the timezone again with `meos_initialize_timezone`.
This PR makes the `pg_tzset` function to always return a copy of the cached timezone, so it doesn't matter if the returned copy is freed.

Fixes timezone cache free

---

meos/src/geo/tpoint_spatialfuncs.c
mobilitydb/test/geo/expected/056_tpoint_spatialfuncs.test.out
mobilitydb/test/geo/expected/056_tpoint_spatialfuncs_tbl.test.out
mobilitydb/test/geo/expected/070_tpoint_spatialrels.test.out
mobilitydb/test/geo/expected/070_tpoint_spatialrels_tbl.test.out
mobilitydb/test/geo/expected/076_tpoint_analytics.test.out
mobilitydb/test/geo/queries/056_tpoint_spatialfuncs_tbl.test.sql

Continuation of the PR #694 by @Diviloper

Improve performance problems identified by Issue #679
